version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '321'
      MYSQL_DATABASE: 'Books_db'
    volumes:
      - ./mydb:/var/lib/mysql

  adminer:
    image: adminer:4.7.8
    restart: always
    ports:
      - 8082:8080